version: '3.6'

services:
  database:
    image: mysql:8
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - config:/etc/mysql
      - data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  app:
    image: node:lts-alpine
    restart: always

    volumes:
      - ./:/app

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT


volumes:
  config:
  data:
